# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_test.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'grpc_test.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fgrpc_test.proto\"\x06\n\x04Void\"\x1a\n\tLongValue\x12\r\n\x05value\x18\x01 \x01(\x03\"\x1b\n\tLongArray\x12\x0e\n\x06values\x18\x01 \x03(\x03\"\x1c\n\x0bStringValue\x12\r\n\x05value\x18\x01 \x01(\t\"(\n\x0c\x43omplexValue\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t2\xcb\x01\n\x0bTestService\x12\x18\n\x08VoidCall\x12\x05.Void\x1a\x05.Void\x12\"\n\x08LongCall\x12\n.LongValue\x1a\n.LongValue\x12\'\n\rLongArrayCall\x12\n.LongArray\x1a\n.LongValue\x12(\n\nStringCall\x12\x0c.StringValue\x1a\x0c.StringValue\x12+\n\x0b\x43omplexCall\x12\r.ComplexValue\x1a\r.ComplexValueb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_test_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VOID']._serialized_start=19
  _globals['_VOID']._serialized_end=25
  _globals['_LONGVALUE']._serialized_start=27
  _globals['_LONGVALUE']._serialized_end=53
  _globals['_LONGARRAY']._serialized_start=55
  _globals['_LONGARRAY']._serialized_end=82
  _globals['_STRINGVALUE']._serialized_start=84
  _globals['_STRINGVALUE']._serialized_end=112
  _globals['_COMPLEXVALUE']._serialized_start=114
  _globals['_COMPLEXVALUE']._serialized_end=154
  _globals['_TESTSERVICE']._serialized_start=157
  _globals['_TESTSERVICE']._serialized_end=360
# @@protoc_insertion_point(module_scope)
