# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import grpc_test_pb2 as grpc__test__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpc_test_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TestServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VoidCall = channel.unary_unary(
                '/TestService/VoidCall',
                request_serializer=grpc__test__pb2.Void.SerializeToString,
                response_deserializer=grpc__test__pb2.Void.FromString,
                _registered_method=True)
        self.LongCall = channel.unary_unary(
                '/TestService/LongCall',
                request_serializer=grpc__test__pb2.LongValue.SerializeToString,
                response_deserializer=grpc__test__pb2.LongValue.FromString,
                _registered_method=True)
        self.LongArrayCall = channel.unary_unary(
                '/TestService/LongArrayCall',
                request_serializer=grpc__test__pb2.LongArray.SerializeToString,
                response_deserializer=grpc__test__pb2.LongValue.FromString,
                _registered_method=True)
        self.StringCall = channel.unary_unary(
                '/TestService/StringCall',
                request_serializer=grpc__test__pb2.StringValue.SerializeToString,
                response_deserializer=grpc__test__pb2.StringValue.FromString,
                _registered_method=True)
        self.ComplexCall = channel.unary_unary(
                '/TestService/ComplexCall',
                request_serializer=grpc__test__pb2.ComplexValue.SerializeToString,
                response_deserializer=grpc__test__pb2.ComplexValue.FromString,
                _registered_method=True)


class TestServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def VoidCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LongCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LongArrayCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StringCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ComplexCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TestServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VoidCall': grpc.unary_unary_rpc_method_handler(
                    servicer.VoidCall,
                    request_deserializer=grpc__test__pb2.Void.FromString,
                    response_serializer=grpc__test__pb2.Void.SerializeToString,
            ),
            'LongCall': grpc.unary_unary_rpc_method_handler(
                    servicer.LongCall,
                    request_deserializer=grpc__test__pb2.LongValue.FromString,
                    response_serializer=grpc__test__pb2.LongValue.SerializeToString,
            ),
            'LongArrayCall': grpc.unary_unary_rpc_method_handler(
                    servicer.LongArrayCall,
                    request_deserializer=grpc__test__pb2.LongArray.FromString,
                    response_serializer=grpc__test__pb2.LongValue.SerializeToString,
            ),
            'StringCall': grpc.unary_unary_rpc_method_handler(
                    servicer.StringCall,
                    request_deserializer=grpc__test__pb2.StringValue.FromString,
                    response_serializer=grpc__test__pb2.StringValue.SerializeToString,
            ),
            'ComplexCall': grpc.unary_unary_rpc_method_handler(
                    servicer.ComplexCall,
                    request_deserializer=grpc__test__pb2.ComplexValue.FromString,
                    response_serializer=grpc__test__pb2.ComplexValue.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TestService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('TestService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TestService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def VoidCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TestService/VoidCall',
            grpc__test__pb2.Void.SerializeToString,
            grpc__test__pb2.Void.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LongCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TestService/LongCall',
            grpc__test__pb2.LongValue.SerializeToString,
            grpc__test__pb2.LongValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LongArrayCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TestService/LongArrayCall',
            grpc__test__pb2.LongArray.SerializeToString,
            grpc__test__pb2.LongValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StringCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TestService/StringCall',
            grpc__test__pb2.StringValue.SerializeToString,
            grpc__test__pb2.StringValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ComplexCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TestService/ComplexCall',
            grpc__test__pb2.ComplexValue.SerializeToString,
            grpc__test__pb2.ComplexValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
